#ifdef __cplusplus
extern "C" {
#endif


#ifndef RAPIDPDFTRANS_H
#define RAPIDPDFTRANS_H

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque document. Do not dereference.
 */
typedef struct RptDocument RptDocument;

/**
 * # Safety
 * `path` and `options_json` are null-terminated UTF-8 strings, or null.
 * The returned handle is freed with `rpt_free`.
 */
struct RptDocument *rpt_open(const char *path, const char *options_json);

/**
 * # Safety
 * `doc` was returned by `rpt_open` and has not been freed.
 * `options_json` is a null-terminated UTF-8 string, or null.
 * The returned string is freed with `rpt_string_free`.
 */
char *rpt_extract(struct RptDocument *doc, const char *options_json);

/**
 * # Safety
 * `doc` was returned by `rpt_open` and has not been freed.
 * `options_json` is a null-terminated UTF-8 string, or null.
 * `RPT_LLM_API_KEY` must be set. An `api_key` field in JSON is ignored.
 * The returned string is freed with `rpt_string_free`.
 */
char *rpt_translate(struct RptDocument *doc, const char *options_json);

/**
 * # Safety
 * `doc` was returned by `rpt_open` and has not been freed.
 * `path` and `options_json` are null-terminated UTF-8 strings, or null.
 * `RPT_LLM_API_KEY` must be set. An `api_key` field in JSON is ignored.
 * Returns 0 after the translated PDF is written.
 */
int rpt_save(struct RptDocument *doc, const char *path, const char *options_json);

/**
 * # Safety
 * `doc` was returned by `rpt_open` and is not used again.
 */
void rpt_free(struct RptDocument *doc);

/**
 * # Safety
 * `text` was returned by `rpt_extract` or `rpt_translate`, or is null.
 */
void rpt_string_free(char *text);

/**
 * Pointer to the last error on this thread. Do not free it.
 */
const char *rpt_last_error(void);

#endif  /* RAPIDPDFTRANS_H */

#ifdef __cplusplus
}
#endif
